add ondemand-oneway-generator-commuter test case

diff --git a/.github/workflows/integration.yaml b/.github/workflows/integration.yaml
--- a/.github/workflows/integration.yaml
+++ b/.github/workflows/integration.yaml
@@ -1,4 +1,4 @@
-name: Integration
+name: Integration Test
 
 on:
   push:
@@ -9,14 +9,14 @@ on:
       - "main"
 
 jobs:
-  integration:
-    name: Run integration tests
+  scheduled-historical-case:
+    name: Run scheduled historical test case
     runs-on: ubuntu-latest
     defaults:
       run:
-        working-directory: ci/simple-case
+        working-directory: ci/scheduled-historical
     steps:
-      - uses: actions/checkout@v3
+      - uses: actions/checkout@v4
 
       - name: Run docker compose up
         run: docker compose up -d
@@ -109,6 +109,145 @@ jobs:
           response=$(curl -sS http://localhost:3000/events)
           line_count=$(echo "$response" | wc -l)
           if [ "$line_count" -ge 200 ]; then
+            echo "Validation passed: Line count is $line_count"
+          else
+            echo "Validation failed: Line count is only $line_count"
+            exit 1
+          fi
+
+  ondemand-oneway-generator-commuter-case:
+    name: Run historical scheduled test case
+    runs-on: ubuntu-latest
+    defaults:
+      run:
+        working-directory: ci/ondemand-oneway-generator-commuter-case
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Run docker compose up
+        run: docker compose up -d
+
+      - name: Wait for service to be ready
+        run: sleep 10
+
+      - name: Setup the ondemand simulation
+        run: |
+          response=$(curl -sS -X POST -F upload_file=@./flex.zip http://localhost:3002/upload)
+          message=$(echo $response | jq -r '.message')
+          if [ "$message" = "successfully uploaded. flex.zip" ]; then
+            echo "Validation passed: $message"
+          else
+            echo "Validation failed: $response"
+            exit 1
+          fi
+
+      - name: Setup the simple planner for ondemand
+        run: |
+          response=$(curl -sS -X POST -F upload_file=@./flex.zip http://localhost:3002/upload)
+          message=$(echo $response | jq -r '.message')
+          if [ "$message" = "successfully uploaded. flex.zip" ]; then
+            echo "Validation passed: $message"
+          else
+            echo "Validation failed: $response"
+            exit 1
+          fi
+
+      - name: Setup the oneway simulation
+        run: |
+          response=$(curl -sS -X POST -F upload_file=@./gbfs.zip http://localhost:3002/upload)
+          message=$(echo $response | jq -r '.message')
+          if [ "$message" = "successfully uploaded. gbfs.zip" ]; then
+            echo "Validation passed: $message"
+          else
+            echo "Validation failed: $response"
+            exit 1
+          fi
+
+      - name: Setup the simple planner for oneway
+        run: |
+          response=$(curl -sS -X POST -F upload_file=@./gbfs.zip http://localhost:3002/upload)
+          message=$(echo $response | jq -r '.message')
+          if [ "$message" = "successfully uploaded. gbfs.zip" ]; then
+            echo "Validation passed: $message"
+          else
+            echo "Validation failed: $response"
+            exit 1
+          fi
+
+      - name: Setup the broker
+        run: |
+          response=$(curl -sS -X POST -H "Content-Type: application/json" -d @./broker_setup.json http://localhost:3000/setup)
+          message=$(echo $response | jq -r '.message')
+          if [ "$message" = "successfully configured." ]; then
+            echo "Validation passed: $message"
+          else
+            echo "Validation failed: $response"
+            exit 1
+          fi
+
+      - name: Start the simulation
+        run: |
+          response=$(curl -sS -X POST http://localhost:3000/start)
+          message=$(echo $response | jq -r '.message')
+          if [ "$message" = "successfully started." ]; then
+            echo "Validation passed: $message"
+          else
+            echo "Validation failed: $response"
+            exit 1
+          fi
+
+      - name: Run the simulation
+        run: |
+          response=$(curl -sS -X POST -H "Content-Type: application/json" http://localhost:3000/run?until=2880)
+          message=$(echo $response | jq -r '.message')
+          if [ "$message" = "successfully run." ]; then
+            echo "Validation passed: $message"
+          else
+            echo "Validation failed: $response"
+            exit 1
+          fi
+
+      - name: Wait
+        run: sleep 15
+
+      - name: Verify the simulation is running successfully
+        run: |
+          response=$(curl -s http://localhost:3000/peek)
+          success=$(echo $response | jq '.success')
+          if [ "$success" = "true" ]; then
+            echo "Validation passed: success"
+          else
+            echo "Validation failed: success is not true"
+            exit 1
+          fi
+
+      - name: Finish the simulation
+        run: |
+          response=$(curl -s -X POST http://localhost:3000/finish)
+          message=$(echo $response | jq -r '.message')
+          if [ "$message" = "successfully finished." ]; then
+            echo "Validation passed: $message"
+          else
+            echo "Validation failed: $response"
+            exit 1
+          fi
+
+      - name: Validate events result
+        run: |
+          response=$(curl -sS http://localhost:3000/events)
+          line_count=$(echo "$response" | wc -l)
+          if [ "$line_count" -ge 200 ]; then
+            echo "Validation passed: Line count is $line_count"
+          else
+            echo "Validation failed: Line count is only $line_count"
+            exit 1
+          fi
+
+      - name: Validate evaluation result
+        run: |
+          response=$(curl -sS http://localhost:3020/evaluation)
+          line_count=$(echo "$response" | wc -l)
+          if [ "$line_count" -ge 2 ]; then
             echo "Validation passed: Line count is $line_count"
           else
             echo "Validation failed: Line count is only $line_count"
